	.file	"GSIMD.cpp"
	.text
	.align 2
	.p2align 4,,15
	.globl	__ZN5GSIMD5GSIMDC2Ev
	.def	__ZN5GSIMD5GSIMDC2Ev;	.scl	2;	.type	32;	.endef
__ZN5GSIMD5GSIMDC2Ev:
LFB1538:
	.cfi_startproc
	rep ret
	.cfi_endproc
LFE1538:
	.globl	__ZN5GSIMD5GSIMDC1Ev
	.def	__ZN5GSIMD5GSIMDC1Ev;	.scl	2;	.type	32;	.endef
	.set	__ZN5GSIMD5GSIMDC1Ev,__ZN5GSIMD5GSIMDC2Ev
	.align 2
	.p2align 4,,15
	.globl	__ZN5GSIMD5GSIMDD2Ev
	.def	__ZN5GSIMD5GSIMDD2Ev;	.scl	2;	.type	32;	.endef
__ZN5GSIMD5GSIMDD2Ev:
LFB1541:
	.cfi_startproc
	rep ret
	.cfi_endproc
LFE1541:
	.globl	__ZN5GSIMD5GSIMDD1Ev
	.def	__ZN5GSIMD5GSIMDD1Ev;	.scl	2;	.type	32;	.endef
	.set	__ZN5GSIMD5GSIMDD1Ev,__ZN5GSIMD5GSIMDD2Ev
	.ident	"GCC: (MinGW.org GCC-6.3.0-1) 6.3.0"
